export { default as Details } from './Details'
export { default as Gallery } from './Gallery'
export { default as Registry } from './Registry'
export { default as Activities } from './Activities'
export { default as Contact } from './Contact'